const players2024 = [
  { rank: 1, name: "Caleb Williams", college: "USC", position: "QB" },
  { rank: 2, name: "Jayden Daniels", college: "LSU", position: "QB" },
  {
    rank: 3,
    name: "Marvin Harrison Jr.",
    college: "Ohio State",
    position: "WR",
  },
  { rank: 4, name: "Malik Nabers", college: "LSU", position: "WR" },
  { rank: 5, name: "Drake Maye", college: "North Carolina", position: "QB" },
  { rank: 6, name: "Rome Odunze", college: "Washington", position: "WR" },
  { rank: 7, name: "Brock Bowers", college: "Georgia", position: "TE" },
  { rank: 8, name: "Dallas Turner", college: "Alabama", position: "EDGE" },
  { rank: 9, name: "Joe Alt", college: "Notre Dame", position: "OT" },
  { rank: 10, name: "Troy Fautanu", college: "Washington", position: "OT" },
  { rank: 11, name: "JC Latham", college: "Alabama", position: "OT" },
  { rank: 12, name: "Laiatu Latu", college: "UCLA", position: "EDGE" },
  { rank: 13, name: "Quinyon Mitchell", college: "Toledo", position: "CB" },
  {
    rank: 14,
    name: "Olumuyiwa Fashanu",
    college: "Penn State",
    position: "OT",
  },
  { rank: 15, name: "Taliese Fuaga", college: "Oregon State", position: "OT" },
  { rank: 16, name: "Byron Murphy II", college: "Texas", position: "DT" },
  { rank: 17, name: "J.J. McCarthy", college: "Michigan", position: "QB" },
  { rank: 18, name: "Terrion Arnold", college: "Alabama", position: "CB" },
  { rank: 19, name: "Chop Robinson", college: "Penn State", position: "EDGE" },
  { rank: 20, name: "Brian Thomas Jr.", college: "LSU", position: "WR" },
  { rank: 21, name: "Adonai Mitchell", college: "Texas", position: "WR" },
  { rank: 22, name: "Jared Verse", college: "Florida State", position: "EDGE" },
  { rank: 23, name: "Cooper DeJean", college: "Iowa", position: "CB" },
  { rank: 24, name: "Tyler Guyton", college: "Oklahoma", position: "OT" },
  { rank: 25, name: "Nate Wiggins", college: "Clemson", position: "CB" },
  { rank: 26, name: "Amarius Mims", college: "Georgia", position: "OT" },
  { rank: 27, name: "Jer'Zhan Newton", college: "Illinois", position: "DT" },
  { rank: 28, name: "Graham Barton", college: "Duke", position: "C" },
  { rank: 29, name: "Darius Robinson", college: "Missouri", position: "EDGE" },
  {
    rank: 30,
    name: "Xavier Legette",
    college: "South Carolina",
    position: "WR",
  },
  { rank: 31, name: "Kool-Aid McKinstry", college: "Alabama", position: "CB" },
  {
    rank: 32,
    name: "Ennis Rakestraw Jr.",
    college: "Missouri",
    position: "CB",
  },
  { rank: 33, name: "Ladd McConkey", college: "Georgia", position: "WR" },
  { rank: 34, name: "Xavier Worthy", college: "Texas", position: "WR" },
  { rank: 35, name: "Payton Wilson", college: "NC State", position: "LB" },
  { rank: 36, name: "Keon Coleman", college: "Florida State", position: "WR" },
  { rank: 37, name: "Jordan Morgan", college: "Arizona", position: "OT" },
  { rank: 38, name: "Braden Fiske", college: "Florida State", position: "DT" },
  { rank: 39, name: "Edgerrin Cooper", college: "Texas A&M", position: "LB" },
  { rank: 40, name: "Bo Nix", college: "Oregon", position: "QB" },
  { rank: 41, name: "Chris Braswell", college: "Alabama", position: "EDGE" },
  { rank: 42, name: "Jonathon Brooks", college: "Texas", position: "RB" },
  { rank: 43, name: "Kingsley Suamataia", college: "BYU", position: "OT" },
  { rank: 44, name: "Ricky Pearsall", college: "Florida", position: "WR" },
  { rank: 45, name: "Kamari Lassiter", college: "Georgia", position: "CB" },
  { rank: 46, name: "Kris Jenkins", college: "Michigan", position: "DT" },
  { rank: 47, name: "T'Vondre Sweat", college: "Texas", position: "DT" },
  { rank: 48, name: "Cedric Gray", college: "North Carolina", position: "LB" },
  { rank: 49, name: "Javon Bullard", college: "Georgia", position: "S" },
  {
    rank: 50,
    name: "Michael Penix Jr.",
    college: "Washington",
    position: "QB",
  },
  { rank: 51, name: "Bralen Trice", college: "Washington", position: "EDGE" },
  { rank: 52, name: "Troy Franklin", college: "Oregon", position: "WR" },
  { rank: 53, name: "Brandon Dorlus", college: "Oregon", position: "DT" },
  {
    rank: 54,
    name: "Marshawn Kneeland",
    college: "Western Michigan",
    position: "EDGE",
  },
  { rank: 55, name: "T.J. Tampa", college: "Iowa State", position: "CB" },
  { rank: 56, name: "Tyler Nubin", college: "Minnesota", position: "S" },
  {
    rank: 57,
    name: "Jackson Powers-Johnson",
    college: "Oregon",
    position: "C",
  },
  { rank: 58, name: "Max Melton", college: "Rutgers", position: "CB" },
  { rank: 59, name: "Cole Bishop", college: "Utah", position: "S" },
  { rank: 60, name: "Trey Benson", college: "Florida State", position: "RB" },
  { rank: 61, name: "Junior Colson", college: "Michigan", position: "LB" },
  { rank: 62, name: "Jaden Hicks", college: "Washington State", position: "S" },
  { rank: 63, name: "Cam Hart", college: "Notre Dame", position: "CB" },
  {
    rank: 64,
    name: "Roger Rosengarten",
    college: "Washington",
    position: "OT",
  },
  { rank: 65, name: "Mekhi Wingo", college: "LSU", position: "DT" },
  { rank: 66, name: "Ja'Tavion Sanders", college: "Texas", position: "TE" },
  { rank: 67, name: "Blake Corum", college: "Michigan", position: "RB" },
  { rank: 68, name: "Michael Hall Jr.", college: "Ohio State", position: "DT" },
  { rank: 69, name: "Zach Frazier", college: "West Virginia", position: "C" },
  { rank: 70, name: "MarShawn Lloyd", college: "USC", position: "RB" },
  { rank: 71, name: "Dominick Puni", college: "Kansas", position: "OT" },
  { rank: 72, name: "Roman Wilson", college: "Michigan", position: "WR" },
  { rank: 73, name: "Christian Haynes", college: "UConn", position: "OG" },
  { rank: 74, name: "Cade Stover", college: "Ohio State", position: "TE" },
  { rank: 75, name: "Maason Smith", college: "LSU", position: "DT" },
  { rank: 76, name: "Brenden Rice", college: "USC", position: "WR" },
  { rank: 77, name: "Jonah Elliss", college: "Utah", position: "EDGE" },
  { rank: 78, name: "Patrick Paul", college: "Houston", position: "OT" },
  { rank: 79, name: "Cooper Beebe", college: "Kansas State", position: "OG" },
  { rank: 80, name: "Austin Booker", college: "Kansas", position: "EDGE" },
  { rank: 81, name: "Mike Sainristil", college: "Michigan", position: "CB" },
  { rank: 82, name: "Jalen McMillan", college: "Washington", position: "WR" },
  { rank: 83, name: "Christian Jones", college: "Texas", position: "OT" },
  { rank: 84, name: "Curtis Jacobs", college: "Penn State", position: "LB" },
  { rank: 85, name: "Javon Baker", college: "UCF", position: "WR" },
  { rank: 86, name: "Kiran Amegadjie", college: "Yale", position: "OT" },
  {
    rank: 87,
    name: "Devontez Walker",
    college: "North Carolina",
    position: "WR",
  },
  { rank: 88, name: "Ruke Orhorhoro", college: "Clemson", position: "DT" },
  {
    rank: 89,
    name: "Jalyx Hunt",
    college: "Houston Christian",
    position: "EDGE",
  },
  { rank: 90, name: "Ja'Lynn Polk", college: "Washington", position: "WR" },
  { rank: 91, name: "Kitan Oladapo", college: "Oregon State", position: "S" },
  { rank: 92, name: "Calen Bullock", college: "USC", position: "S" },
  {
    rank: 93,
    name: "Malachi Corley",
    college: "Western Kentucky",
    position: "WR",
  },
  { rank: 94, name: "Khyree Jackson", college: "Oregon", position: "CB" },
  {
    rank: 95,
    name: "Jeremiah Trotter Jr.",
    college: "Clemson",
    position: "LB",
  },
  { rank: 96, name: "Tykee Smith", college: "Georgia", position: "S" },
  { rank: 97, name: "Ben Sinnott", college: "Kansas State", position: "TE" },
  {
    rank: 98,
    name: "Spencer Rattler",
    college: "South Carolina",
    position: "QB",
  },
  { rank: 99, name: "DeWayne Carter", college: "Duke", position: "DT" },
  {
    rank: 100,
    name: "Brennan Jackson",
    college: "Washington State",
    position: "EDGE",
  },
]

export default players2024
